= React-athon
:toc:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Overview
Welcome to the _react-and-rn-intro_ at Acorn. Here we will go skinny-dipping together in the shallow part of the React and React Native pond.

TODO: Add additional high level information of what we are going to do here

== Prerequisities
=== A decent editor
You will need a fairly decent editor to help out during your React coding, preferably one with content assist and auto-completion. Choose one below. 

[quote]
____
- `Visual Studio Code` https://code.visualstudio.com/download[https://code.visualstudio.com/download]
- `IntelliJ WebStorm` https://www.jetbrains.com/webstorm/[https://www.jetbrains.com/webstorm/] (30 days trial version)

[TIP]
====
If you are in possession of an IntelliJ IDEA Ultimate license, then you are already good to go. Ultimate contains the same javascript support as IntelliJ WebStorm.
====

____

=== Node.js
`Node.js` is an open-source, cross-platform JavaScript run-time environment that executes JavaScript code outside the browser.

[quote]
____
Download and Install Nodejs from https://nodejs.org/en/download/ 
____

== Setting up a basic React project
There are several ways to setup a React project. It usually involves installing and configuring several tools, where the most noteworthy are `WebPack` and `Babel`.


[width="100%"]
|====================

| WebPack | At its core, webpack is a static module bundler for modern JavaScript applications. When webpack processes your application, it internally builds a dependency graph which maps every module your project needs and generates one or more bundles.

| Babel | Babel is a javascript compiler that is mainly used to convert ECMAScript 2015+ code into a backwards compatible version of JavaScript in old browsers or environments. 

|====================

Here we will use Facebook's own template `create-react-app` to quickly setup a project. This will setup everything needed, or more specifically it will create:

* A basic boilerplate React application
* Installations of `Webpack` and `Babel`, configured quietly in the background
* A development server that allow for immediate reload when project files are changed

[quote]
____
*Generate template application*

. Open a terminal in Linux/MacOS or Powershell prompt if you are using Windows.

. Generate the React application
+
[source, bash]
----
npx create-react-app my-app
cd my-app
----

. Start the development server
+
[source, bash]
----
npm start
----

The application should now be accessible via http://localhost:3000
____



