:toc:
:imagesdir: images

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Searching for videos part 2

We do of course need to provide users the ability to search for new videos, anything else would be utterly boring. We will follow a similar pattern as we did with the video list, by sending a callback function to the `SearchBar` component. 

The callback we will create will take a string, the _search term_, perform a `YTSearch`, and when the search is complete, set the resulting videos to the `App` state.

[quote]
____
. In `app.js` (under the constructor), define a new function named `videoSearch(searchTerm)`
+
[source,javascript]
----
videoSearch(searchTerm) {
    
}
----
+
. Refactor the code a bit by moving the `YTSearch` code block from the constructor to the newly created function
+
[source,javascript]
----
constructor(props) {
    super(props);

    this.state = {
        videos: [],
        selectedVideo: null
    };
}

videoSearch(searchTerm) {

    YTSearch({key: API_KEY, term: 'acorntechnology'}, (videos) => {
        this.setState({
            videos: videos,
            selectedVideo: videos[0]
        });
    });
}
----
+
. In the call to `YTSearch`, remove "acorntechnology" and use the `searchTerm` variable instead. Next do a call to `this.videoSearch('acorntechnology')` in the constructor to maintain the original default behaviour.
+
[source,javascript]
----
constructor(props) {
    super(props);

    this.state = {
        videos: [],
        selectedVideo: null
    };

    this.videoSearch('acorntechnology');
}

videoSearch(searchTerm) {
    YTSearch({key: API_KEY, term: searchTerm}, (videos) => {
        this.setState({
            videos: videos,
            selectedVideo: videos[0]
        });
    });
}
----
____

We are now in the position to pass the `videoSearch` function as a callback down to `SearchBar`.

As you may already have guessed, our ambition is to send down the callback, let `SearchBar` capture the search term from the user, use that in the callback function so that state properties `videos` and `selectedVideo` in `App` can be updated, forcing React to rerender. 

[quote]
____
. In `app.js`, add property `onSearchTermChange` to `SearchBar` component, holding the callback function we just made
+
[source,javascript]
----
<SearchBar onSearchTermChange={searchTerm => this.videoSearch(searchTerm)}/>
----
____

When `SearchBar` calls `onSearchTermChange`, it will do so with `searchTerm` and send it right into callback function `videoSearch`, which in turn will perform the `YTSearch` and update the state.

To make the latter work we need to flip over to `search-bar.js` and implement the code there. First of all we should refactor the `<input>` `onChange` to call a function instead, since this will be less bulky.

[quote]
____
. In `search-bar.js`, create a function named  `onInputChange(searchTerm)`
+
[source,javascript]
----
onInputChange(searchTerm) {

}
----
+
. In `search-bar.js`, modify the `onChange` attribute of `<input>` element by adding a call to `onInputChange(searchTerm)`. Submit `event.target.value` as argument to the function
+
[source,javascript]
----
render() {
	return (
	    <div className="search-bar">
	        <input
               value={this.state.searchTerm}
               onChange={event => this.onInputChange(event.target.value)} />
        </div>
    );
}
----
+
Inside `onInputChange(searchTerm)` we want to do two things:

* call `this.setState` in `SearchBar` with captured search term
* call the passed callback function `onSearchTermChange(searchTerm)` with the same term. Note that the callback function is available through the props object
+ 
. Update the `searchTerm` in state
+
[source,javascript]
----
onInputChange(searchTerm) {
    this.setState({searchTerm: searchTerm});
}
----
+ 
. Send captured `searchTerm` into callback
+
[source,javascript]
----
onInputChange(searchTerm) {
    this.setState({searchTerm: searchTerm});
    this.props.onSearchTermChange(searchTerm);
}
----
____

Great! Sweet! That's it! Please do try the searchbar in browser by entering a search term of your choice. It should now function as intended!

[TIP]
Now is the time when it is quite okay to pat yourself on your shoulder. 

== Some finishing touches

We can now see all components on a page, and we can select and play videos. But the css styling is a bit off and could benefit of some loving. 

Also, the search bar in browser acts in a kind of too sensitive way, reacting on every single keypress the user makes. Perhaps we should _throttle_ the search bar somewhat, so it delays the search a bit until the user stops hammering the keyboard.

Let us address these things now.

=== Additional styling

It would be nice with some improvments to the visual presentation: 

* Better alignment of the search bar
* Cursor changes to a pointer and the color goes light grey when hovering over a video in the list.

First let's create CSS style file and link to it from `public/index.html`.

[quote]
____
. In folder `my-app/public`, create file `style.css`

. Add the following content to file.
+
[source, css]
----
.search-bar {
    margin: 20px;
    text-align: center;
}

.search-bar input {
    width: 75%;
}

.video-item img {
    max-width: 64px;
}

.video-detail .details {
    margin-top: 10px;
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 4px;
}

.video-title {
    font-weight: bold;
}

.list-group-item {
    cursor: pointer;
}

.list-group-item:hover {
    background-color: #eee;
}
----
+
. Open `my-app/public/index.html` and add link to the `style.css` file (somewhere inside <head> tag) 
+
[source, html]
----
<link rel="stylesheet" href="style.css">
----
+
. Lastly, in `search-bar.js`, add `className="search-bar"` to the top enclosing `<div>`
+
[source, html]
----
<div className="search-bar">
----
____

Save it all and watch the browser reload

=== Throttling of search input

The search seem to work, but it gives a laggy impression. It performs a search on every keypress we do, which is not very optimal neither from a performance point of view (it fires away a request to Youtube server for every keypress) nor from a user experience perspective. 

Perhaps we should try to throttle the input somewhat so that searches are fired every 2 seconds only, or something close to that? Let's try it.

To our aid we will make use of a javascript library called _lodash_, which contains tons of different utility functions, where on is called `_.debounce` (https://lodash.com/docs/4.17.10#debounce). This creates a "debounced" function that will allow us to delay our search calls.

[quote]
____
. Open a terminal window and install the _lodash_ library
+
[source, bash]
----
# Run this in directory my-app
npm install --save lodash
----
+
. In `app.js`, import _lodash_ (which by convention uses the _ char in import)
+
[source, javascript]
----
import _ from 'lodash';
----
+
. At the top of the render() function, add a debounced function based on our original `videoSearch(searchTerm)`
+
[source, javascript]
----
const debouncedVideoSearch = _.debounce((searchTerm) => {this.videoSearch(searchTerm)}, 300);
----
+
. Change `onSearchTermChange` in `SearchBar` tag to pass `debouncedVideoSearch` instead of `searchTerm => this.videoSearch(searchTerm)`
+
[source, javascript]
----
<SearchBar onSearchTermChange={debouncedVideoSearch}/>
----
+
The complete `App` render() function should now look like this
+
[source, javascript]
----
render() {
    const debouncedVideoSearch = _.debounce((searchTerm) => {this.videoSearch(searchTerm)}, 300);

    return (
        <div>
            <SearchBar onSearchTermChange={debouncedVideoSearch}/>
            <VideoDetail video={this.state.selectedVideo}/>
            <VideoList
                onVideoSelect={selectedVideo => this.setState({selectedVideo})}
                videos={this.state.videos}/>
        </div>
    );
}
----
____

Enter a new search in the search field to see the effect!

[NOTE]
====
The `_.debounce()` function takes two arguments: 

. the function to run
. the number of milliseconds to delay. 

The effect will be that no matter how repeatedly the `<SearchBar onSearchTermChange={videoSearch}/>` will be called, `(searchTerm) => {this.videoSearch(searchTerm)` will only be executed every 300 ms. 

This is actually the same way as a Google search behaves.

====

== The end

You have reached the end of the line, good work! Thank you for hanging on so far. We hope that you feel properly introduced to React by now and want to stay on for the coming React Native and Redux tutorials.

Cheers!

