:toc:
:imagesdir: images

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Searching for videos part 2

We do of course need to provide users the ability to search for new videos, anything else would be utterly boring. We will follow a similar pattern as we did with the video list, by sending a callback function to the `SearchBar` component. 

The callback we will create will take a string, the _search term_, perform a `YTSearch`, and when the search is complete, set the resulting videos to the `App` state.

[quote]
____
. In `app.js` (under the constructor), define a new function named `videoSearch(searchTerm)`
+
[source,javascript]
----
videoSearch(searchTerm) {
    
}
----
+
. Refactor the code a bit by moving the `YTSearch` code block from the constructor to the newly created function
+
[source,javascript]
----
constructor(props) {
    super(props);

    this.state = {
        videos: [],
        selectedVideo: null
    };
}

videoSearch(searchTerm) {

    YTSearch({key: API_KEY, term: 'acorntechnology'}, (videos) => {
        this.setState({
            videos: videos,
            selectedVideo: videos[0]
        });
    });
}
----
+
. In the call to `YTSearch`, remove "acorntechnology" and use the `searchTerm` variable instead. Next do a call to `this.videoSearch('acorntechnology')` in the constructor to maintain the original default behaviour.
+
[source,javascript]
----
constructor(props) {
    super(props);

    this.state = {
        videos: [],
        selectedVideo: null
    };

    this.videoSearch('acorntechnology');
}

videoSearch(searchTerm) {
    YTSearch({key: API_KEY, term: searchTerm}, (videos) => {
        this.setState({
            videos: videos,
            selectedVideo: videos[0]
        });
    });
}
----
____

We are now in the position to pass the `videoSearch` function as a callback down to `SearchBar`.

As you may already have guessed, our ambition is to send down the callback, let `SearchBar` capture the search term from the user, use that in the callback function so that state properties `videos` and `selectedVideo` in `App` can be updated, forcing React to rerender. 

[quote]
____
. In `app.js`, add property `onSearchTermChange` to `SearchBar` component, holding the callback function we just made
+
[source,javascript]
----
<SearchBar onSearchTermChange={searchTerm => this.videoSearch(searchTerm)}/>
----
____

When `SearchBar` calls `onSearchTermChange`, it will do so with `searchTerm` and send it right into callback function `videoSearch`, which in turn will perform the `YTSearch` and update the state.

To make the latter work we need to flip over to `search-bar.js` and implement the code there. First of all we should refactor the `<input>` `onChange` to call a function instead, since this will be less bulky.

[quote]
____
. In `search-bar.js`, create a function named  `onInputChange(searchTerm)`
+
[source,javascript]
----
onInputChange(searchTerm) {

}
----
+
. In `search-bar.js`, modify the `onChange` attribute of `<input>` element by adding a call to `onInputChange(searchTerm)`. Submit `event.target.value` as argument to the function
+
[source,javascript]
----
render() {
	return (
	    <div className="search-bar">
	        <input
               value={this.state.searchTerm}
               onChange={event => this.onInputChange(event.target.value)} />
        </div>
    );
}
----
+
Inside `onInputChange(searchTerm)` we want to do two things:

* call `this.setState` in `SearchBar` with captured search term
* call the passed callback function `onSearchTermChange(searchTerm)` with the same term. Note that the callback function is available through the props object
+ 
. Update the `searchTerm` in state
+
[source,javascript]
----
onInputChange(searchTerm) {
    this.setState({searchTerm: searchTerm});
}
----
+ 
. Send captured `searchTerm` into callback
+
[source,javascript]
----
onInputChange(searchTerm) {
    this.setState({searchTerm: searchTerm});
    this.props.onSearchTermChange(searchTerm);
}
----
____

Great! Sweet! That's it! Please do try the searchbar in browser by entering a search term of your choice. It should now function as intended!


